# PostgreSQL. Versions 9.3 and up are supported.
#
# Configure Using Gemfile
# gem 'activerecord-jdbcpostgresql-adapter'

# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= Rails.application.credentials.dig(:database, :name)  { ENV.fetch("database_name")}  %>
  username: <%= Rails.application.credentials.dig(:database, :username) { ENV.fetch("database_username")} %>
  password: <%= Rails.application.credentials.dig(:database, :password) { ENV.fetch("database_password")} %>
  host: <%= Rails.application.credentials.dig(:database, :host) { ENV.fetch("database_host")} %>
  port: <%= Rails.application.credentials.dig(:database, :port) { ENV.fetch("database_port")} %>
  sslmode: disable


# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: <%= Rails.application.credentials.dig(:database, :name)  { ENV.fetch("database_name")}  %>
  username: <%= Rails.application.credentials.dig(:database, :username) { ENV.fetch("database_username")} %>
  password: <%= Rails.application.credentials.dig(:database, :password) { ENV.fetch("database_password")} %>
  host: <%= Rails.application.credentials.dig(:database, :host) { ENV.fetch("database_host")} %>
  port: <%= Rails.application.credentials.dig(:database, :port) { ENV.fetch("database_port")} %>
  sslmode: disable


production:
  <<: *default
  database: <%= Rails.application.credentials.dig(:database, :name)  { ENV.fetch("database_name")}  %>
  username: <%= Rails.application.credentials.dig(:database, :username) { ENV.fetch("database_username")} %>
  password: <%= Rails.application.credentials.dig(:database, :password) { ENV.fetch("database_password")} %>
  host: <%= Rails.application.credentials.dig(:database, :host) { ENV.fetch("database_host")} %>
  port: <%= Rails.application.credentials.dig(:database, :port) { ENV.fetch("database_port")} %>
  sslmode: disable


